name: Consolidate Songs

on:
  push:
    paths:
      - '**/*_lyrics.txt'
      - '**/*'  # Trigger on any file changes
    paths-exclude:
      - '**/*.gitignore'
      - '**/*.log'
      - '**/*.pyc'
      - '**/__pycache__/**'
      - '**/*.swp'
  workflow_dispatch:

permissions:
  contents: write  # Grants permission to write to the repository

jobs:
  consolidate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run consolidate script
        run: |
          # Ensure we have write permissions
          chmod +w .
          # Run the consolidate script with output file
          python consolidate_songs.py --base-dir . --output-file consolidated_songs.yml
          # Display the processed songs
          cat consolidated_songs.yml

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add consolidated_songs.yml
          git commit -m "Add consolidated songs YAML" || echo "No changes to commit"
          git push
