name: Consolidate Songs

on:
  push:
    paths:
      - '**/*.yml'
  workflow_dispatch: # Allows manual triggering

jobs:
  consolidate:
    runs-on: ubuntu-latest

    steps:
      - name: Debug file paths
        run: ls -R

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Parse and consolidate song files
        run: |
          python consolidate_songs.py

      - name: Print current working directory
        run: pwd

      - name: Run Python script from root
        working-directory: ${{ github.workspace }}
        run: python consolidate_songs.py

      - name: Commit and push consolidated file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add consolidated_songs.yml
          git commit -m "Update consolidated songs file"
          git push
