name: Consolidate Songs

on:
  push:
    paths:
      - '**/*_lyrics.txt'
      - '**/*'  # Trigger on any file changes
    paths-exclude:
      - '**/*.gitignore'
      - '**/*.log'
      - '**/*.pyc'
      - '**/__pycache__/**'
      - '**/*.swp'
  workflow_dispatch:

permissions:
  contents: write  # Grants permission to write to the repository

jobs:
  consolidate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run consolidate script
        run: |
          # Ensure we have write permissions
          chmod +w .
          # Create log directory with proper permissions
          mkdir -p logs
          chmod +w logs
          # Create output directory with proper permissions
          mkdir -p .
          chmod +w .
          # Run the consolidate script with verbose output and absolute paths
          # Disable progress bars for GitHub Actions
          export PROGRESS_DISABLE=1
          # Capture full error output
          python consolidate_songs.py --base-dir $(pwd) --output $(pwd)/consolidated_songs.yml --verbose 2>&1 | tee consolidate_output.txt
          # Display the processed songs
          cat consolidated_songs.yml 2>/dev/null || echo "No consolidated songs file found"
          # Display any log messages
          cat consolidate_songs.log 2>/dev/null || echo "No log file found"
          # Display the captured output
          echo "=== Captured Output ==="
          cat consolidate_output.txt
          # Display any Python error messages
          echo "=== Python Environment ==="
          python -c "print('Python environment is working')"
          # Verify file permissions
          echo "=== File Permissions ==="
          ls -l consolidated_songs.yml 2>/dev/null || echo "No consolidated songs file found"
          # Verify directory permissions
          echo "=== Directory Permissions ==="
          ls -l .

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add consolidated_songs.yml
          git commit -m "Add consolidated songs YAML" || echo "No changes to commit"
          git push
