name: Rename All .yml Files to _lyrics.txt

on:
  push:
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure songs directory exists
        run: |
          if [ ! -d "songs" ]; then
            echo "Error: songs directory does not exist!"
            exit 1
          fi

      - name: Rename all .yml files to _lyrics.txt
        run: |
          cd songs
          echo "Files to be renamed:"
          find . -type f -name "*.yml" -not -path "./.github/*" -not -name "rename-all-yml-to-lyrics.yml"

          find . -type f -name "*.yml" -not -path "./.github/*" -not -name "rename-all-yml-to-lyrics.yml" | while read file; do
            dir=$(dirname "$file")
            base=$(basename "$file" .yml)
            new_file="$dir/${base}_lyrics.txt"
            if mv "$file" "$new_file"; then
              echo "Renamed $file to $new_file"
            else
              echo "Error renaming $file to $new_file" >&2
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add songs/
          git commit -m "Rename all .yml files to _lyrics.txt"
          git push
