name: Rename All .yml Files to _lyrics.txt

on:
  push:
  workflow_dispatch:  # Allows manual triggering

jobs:
  rename:
    runs-on: ubuntu-latest

    # Ensure the job has write permissions to commit changes
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug directory structure
        run: |
          echo "Listing all files in the repository:"
          ls -R

      - name: Rename all .yml files to _lyrics.txt
        run: |
          # Find all .yml files in the root and subdirectories (excluding .github)
          find . -type f -name "*.yml" -not -path "./.github/*" -not -name "rename-all-yml-to-lyrics.yml" | while read file; do
            dir=$(dirname "$file")
            base=$(basename "$file" .yml)
            new_file="$dir/${base}_lyrics.txt"
            mv "$file" "$new_file"
            echo "Renamed $file to $new_file"
          done

      - name: Commit and push changes using GITHUB_TOKEN
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Rename all .yml files to _lyrics.txt" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Fallback using Personal Access Token (PAT) if GITHUB_TOKEN fails
      - name: Commit and push changes using PAT
        if: failure()  # Only run if the previous step fails
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Rename all .yml files to _lyrics.txt" || echo "No changes to commit"
          git push https://oauth2:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
