name: Rename All .yml Files to _lyrics.txt

on:
  push:
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug directory structure
        run: |
          echo "Listing all files in the repository:"
          ls -R

      - name: Rename all .yml files to _lyrics.txt
        run: |
          # Find all .yml files in the root and subdirectories
          find . -type f -name "*.yml" -not -path "./.github/*" -not -name "rename-all-yml-to-lyrics.yml" | while read file; do
            dir=$(dirname "$file")
            base=$(basename "$file" .yml)
            new_file="$dir/${base}_lyrics.txt"
            mv "$file" "$new_file"
            echo "Renamed $file to $new_file"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Rename all .yml files to _lyrics.txt"
          git push
